version: "3.6"
services:
  rbmqa:
    image: currycan/rabbitmq:3.7-management
    container_name: rmqha_node0
    restart: always
    network_mode: "host"
    hostname: rmqha_node0
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    extra_hosts:
      - "rmqha_node0:192.168.43.93"
      - "rmqha_node1:192.168.43.101"
      - "rmqha_node2:192.168.43.141"
    environment:
      - RABBITMQ_NODE_TYPE=disc
      - RABBITMQ_LOGS=/var/lib/rabbitmq/logs/rabbit@rmqha_node0.log
      - RABBITMQ_ERLANG_COOKIE=xMkJQkN!C2RZwC2RZw@1kIxa#5oXgZO0gxrG0
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rmqha_node0

  rbmqb:
    image: currycan/rabbitmq:3.7-management
    container_name: rmqha_node1
    restart: always
    network_mode: "host"
    hostname: rmqha_node1
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    extra_hosts:
      - "rmqha_node0:192.168.43.93"
      - "rmqha_node1:192.168.43.101"
      - "rmqha_node2:192.168.43.141"
    environment:
      - RABBITMQ_NODE_TYPE=ram
      - RABBITMQ_LOGS=/var/lib/rabbitmq/logs/rabbit@rmqha_node1.log
      - RABBITMQ_ERLANG_COOKIE=xMkJQkN!C2RZwC2RZw@1kIxa#5oXgZO0gxrG0
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rmqha_node0

  rbmqc:
    image: currycan/rabbitmq:3.7-management
    container_name: rmqha_node2
    restart: always
    network_mode: "host"
    hostname: rmqha_node2
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    extra_hosts:
      - "rmqha_node0:192.168.43.93"
      - "rmqha_node1:192.168.43.101"
      - "rmqha_node2:192.168.43.141"
    environment:
      - RABBITMQ_NODE_TYPE=ram
      - RABBITMQ_LOGS=/var/lib/rabbitmq/logs/rabbit@rmqha_node2.log
      - RABBITMQ_ERLANG_COOKIE=xMkJQkN!C2RZwC2RZw@1kIxa#5oXgZO0gxrG0
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rmqha_node0
