version: '3.6'
services:
  jenkins:
    image: currycan/jenkins:2.138.1
    container_name: jenkins
    hostname: jenkins
    privileged: true
    restart: always
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
    network_mode: host
    extra_hosts:
      - "jenkins:127.0.0.1"
